### ISSUE TITLE
[Feature Request] Collapsible Text

### ISSUE THREAD

**Issue by dextel2** [tommymcglynn/mortgage-calculator-react#1]
Is it possible to collapse the `<ul> </ul>` which shows the detailed mortgage details?

**Comment by dextel2** [comment]
@tommymcglynn how? or is there any way to pass props to set all default values to 0?

**Comment by tommymcglynn** [comment]
@dextel2 You can set default values like this:

    <MortgageCalculator price={125000} downPayment={10000} interestRate={0.065} />

Regarding the payment schedule, I'll work on an improvement that allows hiding with a prop.

**Comment by dextel2** [comment]
@tommymcglynn Okay, I'll be waiting on that and what about setting the years?

**Comment by tommymcglynn** [comment]
@dextel2 Good catch. The "showPaymentSchedule" prop is now available and props can now be overridden to 0. The months prop also works now. https://github.com/tommymcglynn/mortgage-calculator-react/commit/faa2dcdc7e3b9dcb98c89ba6ccd8c51950c1818f

Please give the new features a try and close this issue if appropriate.

**Comment by dextel2** [comment]
@tommymcglynn sure, can you publish on npmjs?

**Comment by tommymcglynn** [comment]
@dextel2 Done. Version 0.1.1

**Comment by dextel2** [comment]
@tommycglynn
> Please give the new features a try and close this issue if appropriate.

Works perfectly, but when I remove the any given price as any amount to `0` from the form to `0` which is expected, but it does not set Advanced `props` to `0`, is this expected behavior?

other than that, any plans for making it collapsible?

**Comment by tommymcglynn** [comment]
@tommymcglynn I'm not following the prop 0 issue. Can you help me understand?

Regarding collapsible; does that mean add a toggle or button to show/hide the payment schedule?

**Comment by dextel2** [comment]
@tommymcglynn 
Steps to repro
1. Fill all fields including in the advanced options
2. Set `price={0}` and all the fields go back to 0, except those in Advanced and  `Payment Schedule` still shows with the amount in Advanced options

**Comment by tommymcglynn** [comment]
@dextel2 Hm.. I tried but unable to see any weird behavior. Can you share the code to repro?
